apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cicd
  name: myjenkins
  labels:
    app: myjenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myjenkins
  template:
    metadata:
      labels:
        app: myjenkins
    spec:
      containers:
      - name: jenkins
        image: gcr.io/moses-327312/rafabene/myjenkins
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 50000
