kind: Service
apiVersion: v1
metadata:
  namespace: cicd
  name: jenkins
spec:
  selector:
    app: myjenkins
  type: NodePort
  ports:
  - protocol: TCP
    name: slave-port
    port: 50000
    targetPort: 50000
  - protocol: TCP
    name: default-port
    port: 8080
    targetPort: 8080