apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cicd
  name: cloudnative
  labels:
    app: cloudnative
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudnative
  template:
    metadata:
      labels:
        app: cloudnative
    spec:
      containers:
      - name: cloudnative
        image: gcr.io/moses-327312/rafabene/cloudnative
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
        ports:
        - containerPort: 8080
